@startuml

class TestCollection {
    string Name
    Test[] Tests
}

class "Test"  {
    string Name
    string Method
    string Url
    string Body
    Header Headers
    int32 ResponseCode
    string ResponseBody
}

TestCollection --* Test

class "TestConfig" {
    nil WriteConfiguration(TestCollection)
    TestCollection ReadConfiguration()
    ClearTests()
}

class TestRunner {
    RunTest()
    StopTest()
    UpdateTest()
    MonitorAndUpdateStatistics()
}

class Server {
    RunTest()
    StopTest()
    UpdateTest()
    MonitorAndUpdateStatistics()
    ClearTests(0)
}

@enduml