@startuml

package "Remote1" {
    component [ChaosAgent1]
}

package "Remote2" {
    component [ChaosAgent3]
}

package "Remote3" {
    component [ChaosAgent2]
}

package "Management" {
    component "ChaosMaster"
}

[ChaosMaster] --> [ChaosAgent1] : Management Connection
[ChaosMaster] --> [ChaosAgent2] : Management Connection
[ChaosMaster] --> [ChaosAgent3] : Management Connection

actor "DEV"

[DEV] --> [ChaosMaster] : Interacts with Load Test System




@enduml