@startuml

package "RemoteAgents" {
    component [ChaosAgent1]
    component [ChaosAgent3]
    component [ChaosAgent2]
}

package "Management" {
    component "ChaosMaster"
}

package "Monitoring" {
    component [Prometheus]
    component [Grafana]
}

[ChaosMaster] -right--> [ChaosAgent1] : Management Connection
[ChaosMaster] -right--> [ChaosAgent2] : Management Connection
[ChaosMaster] -right--> [ChaosAgent3] : Management Connection

[Prometheus] -right--> [ChaosMaster] : Query metrics
[Grafana] --> [Prometheus] : Graph metrics

actor "DEV"

[DEV] --> [ChaosMaster] : Interacts with Load Test System
[DEV] --> [Grafana] : Observe test metrics




@enduml