@startuml

participant DEV
participant ChaosMaster
participant ChaosMasterTests
participant ChaosAgent
participant ChaosAgent.Config
participant Target
participant Prometheus
participant Grafana

DEV --> ChaosMaster : Create Tests
ChaosMaster --> ChaosMasterTests : Encrypt and store tests
DEV --> ChaosMaster : Start Test Run
ChaosMaster --> ChaosAgent : Deploy Tests
ChaosMaster --> ChaosAgent : Start Tests
ChaosAgent --> ChaosAgent.Config : Get configuration
ChaosAgent --> Target : Execute Tests
ChaosAgent --> ChaosMaster : Push Test metrics
Prometheus --> ChaosMaster : Query Metrics
DEV --> Grafana : View Test Metrics
Grafana --> Prometheus : Get Data to graph
Grafana --> DEV : Visualise Metrics


@enduml