/*
 * Chaos Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "mallekoppie/ChaosAgent/go"

	"github.com/tkanos/gonfig"
)

func GetConfig() (ChaosAgentConfig, error) {
	configuration := ChaosAgentConfig{}
	err := gonfig.GetConf("ChaosAgentConfig.json", &configuration)

	if err != nil {
		log.Print("Error reading config file ChaosAgentConfig.json: %v", err)
		return configuration, err
	}

	return configuration, nil
}

func main() {

	config, configErr := GetConfig()

	if configErr != nil {
		log.Println("Unable to read config: ", configErr)

		return
	}

	log.Printf("Server started on Port: " + config.Port)
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":"+config.Port, router))
}
