/*
 * Chaos Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TestParameters struct {

	// The number of users to simulate
	SimulatedUsers int32 `json:"simulatedUsers"`

	// Name of the test collection to start
	TestCollectionName string `json:"testCollectionName"`
}
