/*
 * Chaos Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/Integration/ChaosAgent/v1/",
		Index,
	},

	Route{
		"AddTests",
		strings.ToUpper("Put"),
		"/Integration/ChaosAgent/v1/configure",
		AddTests,
	},

	Route{
		"GetTestStatus",
		strings.ToUpper("Get"),
		"/Integration/ChaosAgent/v1/test",
		GetTestStatus,
	},

	Route{
		"IsAlive",
		strings.ToUpper("Get"),
		"/Integration/ChaosAgent/v1/health",
		IsAlive,
	},

	Route{
		"StartTestRun",
		strings.ToUpper("Post"),
		"/Integration/ChaosAgent/v1/test",
		StartTestRun,
	},

	Route{
		"StopTestRun",
		strings.ToUpper("Delete"),
		"/Integration/ChaosAgent/v1/test",
		StopTestRun,
	},

	Route{
		"UpdateTestRun",
		strings.ToUpper("Put"),
		"/Integration/ChaosAgent/v1/test",
		UpdateTestRun,
	},
}
