/*
 * Chaos Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Test struct {
	Name string `json:"name"`

	Method string `json:"method"`

	Url string `json:"url"`

	Body string `json:"body,omitempty"`

	Headers []Header `json:"headers,omitempty"`

	// The expected HTTP Status code that is returned
	ResponseCode int `json:"responseCode"`

	// The expected body. This probably won't work so well
	ResponseBody string `json:"responseBody,omitempty"`
}
