platform:
  log:
    # debug
    # info
    # warn
    # error
    level: info
    filepath: "./log.txt"
  http:
    server:
      listeningaddress: 0.0.0.0:9111
      tlscertfilename: ""
      tlskeyfilename: ""
      tlsenabled: false
    clients:
      - id: default
        tlsverify: false
        maxidleconnections: 10
        requesttimeout: 10
      - id: custom
        tlsverify: false
        maxidleconnections: 10
        requesttimeout: 10
  auth:
    server:
      oauth:
        enabled: false
        idpwellknownurl: ""
        clientid: ""
        allowedalgorithms:
          - rs256
          - rs384
      # Basic Auth adds 75 - 80 ms to the response time - queue sad face :(
      # Passwords must be hashed using bcrypt. Unencrypted passwords will not work
      basic:
        enabled: false
        allowedusers:
          test: $2a$10$zX3HVDhKWRg2YWrf5VuHYutOOfj4DY.Wk7CsFgEFNgFmQqKBEumJG
          user2: pass2
    client:
      oauth:
        owntokens:
          - id: default
            idpwellknownurl: ""
            clientid: test client ID
            clientsecret: some secret
            username: test username
            password: testpassword
          - id: exsternalApi
            idpwellknownurl: ""
            clientid: remoteClientID
            clientsecret: remote secret
            username: test username
            password: testpassword
  component:
    componentname: Example platform service
  database:
    boltdb:
      enabled: true
      filename: ./database.db

ChaosMasterConfiguration:
  grafana_url: test
  prometheus_url: test
  idp_url: test
  idp_client_id: test
  mongo_db_name: local
  mongo_db_host: localhost
  mongo_db_port: 1
  mongo_db_username: admin
  mongo_db_password: admin
  vault_enabled: false
  consul_url:  test
  consul_token: test
