/*
 * Chaos Agent
 *
 * API is used to create load for other APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Header struct {

	Name string `json:"name,omitempty"`

	Value string `json:"value,omitempty"`
}
